version: '2.1'
services:
  app:
    container_name: full_app
    restart: unless-stopped
    build:
      # build the image from Dockerfile
      context: .
      dockerfile: Dockerfile
    working_dir: /flask-api
    environment:
      # set database credentials from .env
      DB_HOSTNAME: ${DB_HOSTNAME} 
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./flask-api:/flask-api
    ports:
      # bind on our 5000 port 
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: full_db
    # from mysql 5.7 image
    image: mysql:5.7
    volumes:
        # pass volume named db to mysql container
      - db:/var/lib/mysql
    restart: unless-stopped

    environment:
      # credentials
      - MYSQL_ROOT_HOST=${DB_HOSTNAME} 
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 3s
      timeout: 45s
      retries: 5

volumes:
  db: