version: '3.8'

services:
  db:
    container_name: full-db
    image: mysql:8
    restart: always

    environment:
      # credentials
      - MYSQL_ROOT_HOST=${DB_HOSTNAME} 
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql

  app:
    container_name: full-app
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /flask-api
    restart: unless-stopped
    volumes:
      - ./flask-api:/flask-api
    environment:
      # set database credentials from .env
      DB_HOSTNAME: ${DB_HOSTNAME} 
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    ports:
      - '5000:5000'

volumes:
  db: